from pathlib import Path


class WorkerWorkspace:
    """
    Handles files generated by individual workers.
    """

    def __init__(self):
        self.base_path = Path("projects")

    def create(self, project_id, worker):
        """
        Create a workspace for a worker.
        """

        worker_path = (
            self.base_path
            / str(project_id)
            / "workers"
            / f"worker_{worker.id}"
        )

        worker_path.mkdir(
            parents=True,
            exist_ok=True
        )

        return worker_path

    def save_output(self, project_id, worker):
        """
        Save the worker's generated output.
        """

        if not worker.output_file:
            return None

        if worker.output_content is None:
            return None

        worker_path = (
            self.base_path
            / str(project_id)
            / "workers"
            / f"worker_{worker.id}"
        )

        worker_path.mkdir(
            parents=True,
            exist_ok=True
        )

        output_path = (
            worker_path
            / worker.output_file
        )

        output_path.write_text(
            worker.output_content,
            encoding="utf-8"
        )

        print(
            f"[Worker Workspace] "
            f"Saved: {output_path}"
        )

        return output_path