class WorkerEngine:
    """
    Executes workers and generates project artifacts.
    """

    def run(self, worker):

        print(
            f"[Worker Engine] "
            f"{worker.role} AI started..."
        )

        if worker.role == "HTML":

            worker.output_file = "index.html"

            worker.output_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nexus Generated Website</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <main>
        <h1>Nexus Generated Website</h1>
        <p>This website was generated by Nexus.</p>

        <button id="helloButton">
            Click Me
        </button>
    </main>

    <script src="script.js"></script>

</body>
</html>
"""

            result = (
                "index.html generated successfully."
            )

        elif worker.role == "CSS":

            worker.output_file = "style.css"

            worker.output_content = """* {
    box-sizing: border-box;
}

body {
    margin: 0;
    min-height: 100vh;

    display: flex;
    align-items: center;
    justify-content: center;

    font-family: Arial, sans-serif;
    background: #111;
    color: white;
}

main {
    text-align: center;
}

h1 {
    margin-bottom: 10px;
}

p {
    color: #aaa;
}

button {
    margin-top: 20px;
    padding: 12px 20px;

    border: none;
    border-radius: 8px;

    cursor: pointer;

    font-size: 16px;
}
"""

            result = (
                "style.css generated successfully."
            )

        elif worker.role == "JavaScript":

            worker.output_file = "script.js"

            worker.output_content = """const button =
    document.getElementById("helloButton");

button.addEventListener("click", () => {
    alert("Hello from Nexus!");
});
"""

            result = (
                "script.js generated successfully."
            )

        else:

            worker.output_file = (
                f"worker_{worker.id}.txt"
            )

            worker.output_content = (
                f"Worker Role: {worker.role}\n"
                f"Mission: {worker.mission}\n"
            )

            result = (
                f"{worker.output_file} "
                f"generated successfully."
            )

        print(
            f"[Worker Engine] "
            f"{worker.role} AI finished."
        )

        return result